### ISSUE TITLE
☂️ Reorg resistance of Ethereum backend

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/go-perun#19]
The Ethereum backend is currently build on the assumption that a transaction cannot be reverted. While this may be true for local testnets, it is not true for public testnets and the Ethereum mainnet, where block reorgs can happen.

We should make the Ethereum backend work with Ethereum nets where reorgs appear. An idea how to implement this is as follows: We introduce a parameter `ConfirmationBlockDepth`. Whenever go-perun accesses on-chain state, we only provide on-chain state if it is at least `ConfirmationBlockDepth` blocks old.

The following appear to be relevant places in the code where on-chain state is accessed:
- Contract validation: ValidateAdjudicator, ValidateAssetHolder
- Event subscription: Watch, Filter
- Contract deployment: WaitDeployed
- Transaction confirmation: ConfirmTransaction

Added by @ggwpez:  
The current road map for this issue looks like this:  
- [x] Reorg resistance in *go-perun*
  - [x] Simulated reorgs in *go-ethereum* https://github.com/ethereum/go-ethereum/pull/22624
    - [x] Tests
  - [x] Resistant Event Subs #40
    - [x] Use in *go-perun* #85
    - [x] Expose BoundContract #41 (done but not merged)
    - [x] Generic Event Subs #39 (done but not merged)
      - [x] Use in *go-perun* #84 
  - [x] Resistant TX confirming 
    - [x] Generic TX confirming #97 (partially done with `ConfirmTx` and `WaitDeployed`)
    - [x] Resistant contract deployment #99
    - [x] Fix finality depth #98
  - [x] Reorg Tests
    - [x] Reverting
    - [x] Reordering Events
    - [x] Reordering TX
    - [x] Header subscription

**Comment by ggwpez** [comment]
Biggest point missing: How to test this.  
Currently we use the simulated block chain from `go-ethereum`. Im evaluating if it can do reorgs [here](https://github.com/hyperledger-labs/go-perun/compare/dev...perun-network:tmp/test-revert#diff-5008ce6fb9709c025c99e0bd5c3175fe257ad88a1114bf07b68f239e5f87a475R129).

**Comment by ggwpez** [comment]
After adding a `Reorg(depth)` function to *go-ethereum*, i was able to get a legit reorg on the simulated backend.  
It removed the previous events with a `removed: true` event.  
It does seem, however, that the TX do not end up in the mempool again, and therefore needs to be resent by the user.   
Im not sure if this is normal behaviour in a geth node or an incapability of the simulated chain.

Looking at chainlink, they periodically pull the mempool status to check that the TX is still in and resend if not.  
We therefore probably need something similar to their BPTM (bullet proof TX manager).

**Comment by ggwpez** [comment]
The current road map for this issue looks like this:  
- [ ] Reorg resistance in *go-perun*
  - [ ] Simulated reorgs in *go-ethereum*
    - [ ] Tests
  - [ ] Resistant Event Subs
    - [ ] Generic Event Subs
  - [ ] Resistant TX confirming
    - [ ] Generic TX confirming (partially done with `ConfirmTx` and `WaitDeployed`)
  - [ ] Reorg Tests
    - [ ] Reverting
    - [ ] Reordering Events
    - [ ] Reordering TX
    - [ ] Header subscription

**Comment by matthiasgeihs** [comment]
All done
