### ISSUE TITLE
☂️ Create abstractions to make the wire serialization protocol exchangable.

### ISSUE THREAD

**Issue by manoranjith** [hyperledger-labs/go-perun#233]
### Location
[wire], [pkg/io], [wire/net]

### Motivation

Currently, wire messages in go-perun are encoded/decoded using a home-baked. When developing alternate implementations of the perun channel client, in a different programming language, the encoders and decoders have to be re-implemented in that language.

If we are able to exchange the custom format for standard ones like "protocol buffers", the messages can be defined once and the encoders/decoders can be generated for different programming languages. This will eliminate the overhead of implementing and maintaining the encoders/decoders in multiple languages.

However, this it is currently not possible to exchange custom format for a different one, as the necessary abstractions are missing. The scope of this task is to introduce the necessary abstractions.

### Details

Abstractions necessary for making the wire serialization format exchangeable has been discussed and accepted in [proposal#5](https://github.com/hyperledger-labs/perun-proposals/blob/main/design/005-Wire-Encoding-Abstraction.md).

This can be implemented in 6 steps, each involving one PR. This an umbrella issue to track the complete task.

- [x] Step 1
  - [x] Refactor Address,Asset, Data, Action types from (En|De)coder to binary.(Un)marshaler. Discussed in this [comment](https://github.com/hyperledger-labs/go-perun/issues/233#issuecomment-943628627) and tracked in #257.
  - [x] Move out `pkg/io` package to `wire/perun`. #285 
  - [x] Package `pkg/io/test`, which defines generic tests for encoders/decoders is moved to `wire/test` package. #287 
    
- [x] Step 2 #297 

    - [x] Define `EnvelopeSerializer` interface.
    ```
   type EnvelopeSerializer interface {
        Encode(io.Writer, Envelope) error
        Decode(io.Reader) (Envelope, error)
   }
   ```
    - [x] Add a unexported package level variable that holds an instance of `EnvelopeSerializer` and an exported function
    `SetEnvelopeSerializer`, for setting it. The function should panic, if invoked more than once.
    - [x] Implement the `EnvelopeSerializer` for perunio serialization format. The implementation should be placed in new package :`wire/perunio/serializer`. Because, package `wire/perunio` cannot import package `wire`.
    - [x] Add an `init` function in package `wire/perunio/serializer`, which sets the `wire.enveloperSerializer` to perunio envelope serializer. 

    *Remark:* It would be nicer to have the `EnvelopeSerializer` implementation directly in package `wire/perunio`. However, this might require some refactoring (as described in step 7) and hence could be done later.

- [x] Step 3 #297 
  - [x] Replace the `wire.(Encode/Decode)` methods with functions `EncodeEnvelope` and `DecodeEvelope`.
  - [x] Update the `Recv` and `Send` on `ioconn` in the `wire/net` package to use the newly defined functions instead of `wire.(Encode/Decode)` methods.

- [x] Step 4 #298 
  - [x] Use `(Un)MarshalBinary` function instead of `perunio.(En|De)code` in places where data is to be converted to/from binary representation, but need not be written to the wire. In particular, see https://github.com/hyperledger-labs/go-perun/commit/75150e1bf63119c1c910291090d3b40133e58bf4 and https://github.com/hyperledger-labs/go-perun/commit/1dc079734cc6b44cb6636b79dd5c3ad0151cd977.

- Step 5 (Can be done later)
  - Introduce an abstract type for `wallet.Sig`. Described and tracked in #292.

- Step 6 (Can be done later)
  - Move the decoders map from the `wire` package to the `wire/perun` package.
  - In the `wire` package, decode envelopes instead of messages.

- Step 7 (Can be done later)
   From the `client` package,
   - Move the message definitions to the `wire` package and
   - Move the encoder/decoder implementations to the `wire/perun` package.
   - After these changes, merge `wire/perunio/serializer` package into `wire/perunio`. Because, now it would be possible for `wire/perunio` package to import `wire` package.

Notes:

1. [x] Regarding persistence, we can continue to use the perunio protocol as that is used for wire serialization. This should continue to work without any additional changes unless we implement step 7. When we implement step 7, we could rethink how we should handle it.

2. [x] Make `ProposalID` independent of perunio #301 
3. [x] Export all relevant all message types #302

**Comment by manoranjith** [comment]
Because, the documentation of [Data](https://github.com/hyperledger-labs/go-perun/blob/624560fe6ff679b9fe50301435fc5ab96d82367b/channel/state.go#L54) says it will be decoded by the App Backend and that of `Action` says it will be decoded by the action app backend. 

Which means, the encoding/decoding implementations for these packages are not defined by the wire protocol, but by the app backend ?
@sebastianst

**Comment by sebastianst** [comment]
Yes I think we have to regard this as two different levels of en/decoding. It is app specific how to en/decode the data for itself, and the resulting/source `[]byte` slice should then be embedded into the message en/decoding. So I think every wire message en/decoding implementation has to use these `Asset` and `App` en/decodings.

**Comment by manoranjith** [comment]
@sebastianst Regarding the `NewAddress` factories, we could also do it other way around: Instead of a `NewAddress` factory, provide a `DecodeAddress` method on the backend. However, it is idiomatic in go, to instantiate an object and unmarshall/decode using it. Because, this way, the implementation of decode is coupled only to the concerned type.

**Comment by manoranjith** [comment]
@Points from discussion with @matthiasgeihs

Currently, the `Encoder/Decoder` interfaces does two things (blockchain-dependent data-serialization) and (wire serialization). Hence, we need to refactor by replacing it with `encoding.BinaryMarshaler/encoding.BinaryUnmarshal` that does blockchain dependent data-serialization. Since, `Binarymarshaler` would output a byte array, it can be directly serialized/de-serialized by the wire package without any additional information.

After this refactor, it should be easier to create abstractions for the wire serialization.

**Comment by matthiasgeihs** [comment]
## Update after meeting on Jan 11

- Postpone step 2 - 4.

- Replace Step 5 and 6 with the following:

### Introduce wire.Encoder
1. In package `wire`, add Encoder interface.
```go
type Encoder interface {
	Encode(io.Writer, *Envelope) error
	Decode(io.Reader) (*Envelope, error)
}
```
Also add method `wireSetEncoder` for setting the encoder globally, and methods `wireEncodeEnvelope` and `wire.DecodeEnvelope`. An example is given in https://github.com/hyperledger-labs/go-perun/commit/b5f9f35c69215a2c823d910ac0445abc44137ff2.

2. Implement `Encoder` for `perunio`.
In package `wire/perunio`, create an implementation of interface `wire.Encoder` that uses the `perunio` encoding.
An example is given in https://github.com/hyperledger-labs/go-perun/commit/b5f9f35c69215a2c823d910ac0445abc44137ff2.
**Remark**: Currently, the perun encoding logic is contained in `wire/perunio`, but the Encoder implementation is in a sub package. It might be nicer to have the encoder implementation directly in package `wire/perunio` (or maybe even rename to something else, like `wire/perun` or `wire/default`), and maybe move the Perun encoding logic back to `pkg/io`. However, this might require some refactoring and could also be done in a later issue.

3. Change `net.ioConn` to use `wire.EncodeEnvelope` and `wire.DecodeEnvelope`.
An example is given in https://github.com/hyperledger-labs/go-perun/commit/b5f9f35c69215a2c823d910ac0445abc44137ff2.

The following is to be considered as well:
- Use (Un)MarshalBinary where applicable.
  - https://github.com/hyperledger-labs/go-perun/commit/75150e1bf63119c1c910291090d3b40133e58bf4
  - https://github.com/hyperledger-labs/go-perun/commit/1dc079734cc6b44cb6636b79dd5c3ad0151cd977
- How do we derive ProposalID? Problem: Currently it depends on perunio.
  - For reference, have a look at https://github.com/hyperledger-labs/go-perun/commit/8bc3772b8e35c54cba53a8502842107e9db58f80.
- Which encoding do we use for persistence?

@manoranjith Please check my additions and modify your issue description as necessary.

**Comment by matthiasgeihs** [comment]
all tasks done
